# analysis/detector.py

import unidecode

# Dicionário que você forneceu (vou chamar de DOMAIN_SYNONYMS)
DOMAIN_SYNONYMS = {
  # LOCALIZAÇÃO E ENDEREÇO
  'cep': ['CEP', 'Código Postal', 'Postal Code', 'ZIP Code', 'Zip'],
  'cidade': ['Cidade', 'Município', 'City', 'Localidade', 'Municipal'],
  'estado': ['Estado', 'UF', 'Unidade Federativa', 'State', 'Província', 'Federação'],
  'pais': ['País', 'Country', 'Nação', 'Nation', 'Nacionalidade'],
  'endereco': ['Endereço', 'Address', 'Logradouro', 'Rua', 'Street', 'Avenida', 'Av'],
  'bairro': ['Bairro', 'Distrito', 'Neighborhood', 'District', 'Zone', 'Area'],
  'numero': ['Número', 'Number', 'Nº', 'No', 'Num', '#'],
  'complemento': ['Complemento', 'Complement', 'Observação', 'Obs', 'Adicional'],
  'regiao': ['Região', 'Region', 'Zona', 'Zone', 'Area', 'Territory'],
  'coordenadas': ['Coordenadas', 'Coordinates', 'GPS', 'Latitude', 'Longitude'],
  'referencias': ['Referências', 'References', 'Ponto de Referência', 'Landmark'],

  # NEGÓCIO E EMPRESA
  'loja': ['Loja', 'Franquia', 'Nome', 'Store', 'Franchise', 'Unidade', 'Shop'],
  'categoria': ['Categoria', 'Tipo', 'Segmento', 'Category', 'Type', 'Classification'],
  'empresa': ['Empresa', 'Company', 'Corporação', 'Organização', 'Corporation', 'Firm'],
  'razao_social': ['Razão Social', 'Corporate Name', 'Nome Empresarial', 'Legal Name'],
  'nome_fantasia': ['Nome Fantasia', 'Trade Name', 'Brand Name', 'Commercial Name'],
  'cnpj': ['CNPJ', 'CPF', 'Tax ID', 'Corporate ID', 'Federal ID'],
  'inscricao_estadual': ['Inscrição Estadual', 'IE', 'State Registration', 'State ID'],
  'inscricao_municipal': ['Inscrição Municipal', 'IM', 'Municipal Registration'],
  'filial': ['Filial', 'Branch', 'Subsidiary', 'Sucursal', 'Unit'],
  'matriz': ['Matriz', 'Headquarters', 'Head Office', 'Main Office'],
  'porte': ['Porte', 'Size', 'Scale', 'Company Size'],
  'ramo': ['Ramo', 'Business Line', 'Industry', 'Sector'],
  'atividade': ['Atividade', 'Activity', 'Business Activity', 'Operation'],
  'fundacao': ['Fundação', 'Founded', 'Establishment', 'Creation Date'],
  'capital_social': ['Capital Social', 'Share Capital', 'Equity Capital'],

  # TECNOLOGIA DA INFORMAÇÃO (TI)
  'sistema': ['Sistema', 'System', 'Software', 'Application', 'App'],
  'servidor': ['Servidor', 'Server', 'Host', 'Machine', 'Node'],
  'banco_dados': ['Banco de Dados', 'Database', 'DB', 'Schema', 'DataBase'],
  'aplicacao': ['Aplicação', 'Application', 'App', 'Sistema', 'Program'],
  'usuario': ['Usuário', 'User', 'Login', 'Account', 'Username'],
  'senha': ['Senha', 'Password', 'Pass', 'Authentication', 'Auth'],
  'ip': ['IP', 'Endereço IP', 'IP Address', 'Network Address'],
  'porta': ['Porta', 'Port', 'Service Port', 'TCP Port', 'UDP Port'],
  'protocolo': ['Protocolo', 'Protocol', 'Communication Protocol'],
  'api': ['API', 'Interface', 'Web Service', 'Endpoint', 'REST'],
  'versao': ['Versão', 'Version', 'Release', 'Build', 'Revision'],
  'licenca': ['Licença', 'License', 'Subscription', 'Plan', 'Key'],
  'backup': ['Backup', 'Cópia de Segurança', 'Restore Point', 'Archive'],
  'log': ['Log', 'Registro', 'Audit Trail', 'Event Log', 'History'],
  'erro': ['Erro', 'Error', 'Exception', 'Bug', 'Issue'],
  'status': ['Status', 'Estado', 'Condition', 'State', 'Situation'],
  'tipo_dispositivo': ['Tipo de Dispositivo', 'Device Type', 'Hardware Type'],
  'so': ['Sistema Operacional', 'SO', 'OS', 'Operating System'],
  'cpu': ['CPU', 'Processador', 'Processor', 'Core', 'Microprocessor'],
  'memoria': ['Memória', 'Memory', 'RAM', 'Storage', 'Cache'],
  'disco': ['Disco', 'Hard Drive', 'Storage', 'HD', 'SSD', 'HDD'],
  'rede': ['Rede', 'Network', 'LAN', 'WAN', 'WiFi', 'Ethernet'],
  'firewall': ['Firewall', 'Security', 'Protection', 'Firewall Rules'],
  'antivirus': ['Antivírus', 'Antivirus', 'Security Software', 'Protection'],
  'dominio': ['Domínio', 'Domain', 'URL', 'Website', 'Site'],
  'ssl': ['SSL', 'Certificate', 'Security Certificate', 'HTTPS'],
  'ftp': ['FTP', 'File Transfer', 'SFTP', 'Transfer Protocol'],
  'vpn': ['VPN', 'Virtual Private Network', 'Tunnel'],
  'proxy': ['Proxy', 'Gateway', 'Intermediary'],
  'dns': ['DNS', 'Domain Name System', 'Name Server'],
  'dhcp': ['DHCP', 'Dynamic IP', 'IP Assignment'],
  'mac_address': ['MAC Address', 'Physical Address', 'Hardware Address'],

  # FINANÇAS
  'receita': ['Receita', 'Revenue', 'Income', 'Faturamento', 'Earnings'],
  'despesa': ['Despesa', 'Expense', 'Cost', 'Gasto', 'Expenditure'],
  'lucro': ['Lucro', 'Profit', 'Gain', 'Earnings', 'Net Income'],
  'prejuizo': ['Prejuízo', 'Loss', 'Deficit', 'Negative Result'],
  'investimento': ['Investimento', 'Investment', 'Capital', 'Application'],
  'ativo': ['Ativo', 'Asset', 'Property', 'Resource'],
  'passivo': ['Passivo', 'Liability', 'Debt', 'Obligation'],
  'patrimonio': ['Patrimônio', 'Equity', 'Net Worth', 'Assets'],
  'capital': ['Capital', 'Capital Stock', 'Equity', 'Investment'],
  'divida': ['Dívida', 'Debt', 'Loan', 'Liability', 'Borrowing'],
  'credito': ['Crédito', 'Credit', 'Loan', 'Financing'],
  'debito': ['Débito', 'Debit', 'Charge', 'Withdrawal'],
  'saldo': ['Saldo', 'Balance', 'Amount', 'Remaining'],
  'fluxo_caixa': ['Fluxo de Caixa', 'Cash Flow', 'Cash Movement'],
  'conta': ['Conta', 'Account', 'Account Number', 'Banking Account'],
  'banco': ['Banco', 'Bank', 'Financial Institution'],
  'agencia': ['Agência', 'Branch', 'Agency', 'Bank Branch'],
  'juros': ['Juros', 'Interest', 'Interest Rate', 'Finance Charge'],
  'taxa': ['Taxa', 'Rate', 'Fee', 'Charge', 'Commission'],
  'multa': ['Multa', 'Fine', 'Penalty', 'Late Fee'],
  'desconto': ['Desconto', 'Discount', 'Rebate', 'Reduction'],
  'pagamento': ['Pagamento', 'Payment', 'Settlement', 'Transaction'],
  'recebimento': ['Recebimento', 'Receipt', 'Collection', 'Income'],
  'fatura': ['Fatura', 'Invoice', 'Bill', 'Statement'],
  'nota_fiscal': ['Nota Fiscal', 'Invoice', 'Tax Document', 'Fiscal Note'],
  'orcamento': ['Orçamento', 'Budget', 'Quote', 'Estimate'],
  'planejamento': ['Planejamento', 'Planning', 'Forecast', 'Strategy'],
  'projecao': ['Projeção', 'Projection', 'Forecast', 'Prediction'],
  'roi': ['ROI', 'Return on Investment', 'Retorno sobre Investimento'],
  'margem': ['Margem', 'Margin', 'Markup', 'Profit Margin'],
  'cotacao': ['Cotação', 'Quote', 'Exchange Rate', 'Price Quote'],
  'moeda': ['Moeda', 'Currency', 'Money', 'Cash'],
  'cambio': ['Câmbio', 'Exchange', 'Currency Exchange'],
  'financiamento': ['Financiamento', 'Financing', 'Loan', 'Credit'],
  'emprestimo': ['Empréstimo', 'Loan', 'Borrowing', 'Credit'],
  'cartao_credito': ['Cartão de Crédito', 'Credit Card', 'Card'],
  'cheque': ['Cheque', 'Check', 'Bank Draft'],
  'transferencia': ['Transferência', 'Transfer', 'Wire Transfer'],
  'deposito': ['Depósito', 'Deposit', 'Bank Deposit'],
  'saque': ['Saque', 'Withdrawal', 'Cash Withdrawal'],
  'pix': ['PIX', 'Instant Payment', 'Electronic Transfer'],
  'ted': ['TED', 'Electronic Transfer', 'Bank Transfer'],
  'doc': ['DOC', 'Document Transfer', 'Bank Document'],

  # ECONOMIA
  'pib': ['PIB', 'GDP', 'Produto Interno Bruto', 'Gross Domestic Product'],
  'inflacao': ['Inflação', 'Inflation', 'Price Index', 'CPI'],
  'deflacao': ['Deflação', 'Deflation', 'Price Decrease'],
  'crescimento': ['Crescimento', 'Growth', 'Expansion', 'Development'],
  'recessao': ['Recessão', 'Recession', 'Economic Downturn'],
  'mercado': ['Mercado', 'Market', 'Marketplace', 'Trading'],
  'setor': ['Setor', 'Sector', 'Industry', 'Business Sector'],
  'economia': ['Economia', 'Economy', 'Economic', 'Financial System'],
  'macro': ['Macroeconomia', 'Macro', 'Macroeconomic'],
  'micro': ['Microeconomia', 'Micro', 'Microeconomic'],
  'oferta': ['Oferta', 'Supply', 'Offer', 'Availability'],
  'demanda': ['Demanda', 'Demand', 'Request', 'Need'],
  'preco': ['Preço', 'Price', 'Cost', 'Value', 'Amount'],
  'custo': ['Custo', 'Cost', 'Expense', 'Price'],
  'valor': ['Valor', 'Value', 'Worth', 'Amount', 'Price'],
  'indice': ['Índice', 'Index', 'Indicator', 'Rate'],
  'indicador': ['Indicador', 'Indicator', 'Metric', 'KPI'],
  'balanca_comercial': ['Balança Comercial', 'Trade Balance', 'Commercial Balance'],
  'exportacao': ['Exportação', 'Export', 'Outbound Trade', 'Foreign Sales'],
  'importacao': ['Importação', 'Import', 'Inbound Trade', 'Foreign Purchase'],
  'cambio_economia': ['Câmbio', 'Exchange', 'Foreign Exchange', 'FX'],
  'bolsa': ['Bolsa', 'Stock Exchange', 'Market', 'Stock Market'],
  'acao': ['Ação', 'Stock', 'Share', 'Equity'],
  'dividendo': ['Dividendo', 'Dividend', 'Profit Share'],
  'commodities': ['Commodities', 'Raw Materials', 'Primary Products'],
  'selic': ['SELIC', 'Base Interest Rate', 'Central Bank Rate'],
  'cdi': ['CDI', 'Interbank Rate', 'Daily Rate'],
  'ipca': ['IPCA', 'Consumer Price Index', 'Inflation Index'],
  'igp': ['IGP', 'General Price Index'],

  # RECURSOS HUMANOS (RH)
  'funcionario': ['Funcionário', 'Employee', 'Worker', 'Staff', 'Personnel'],
  'colaborador': ['Colaborador', 'Collaborator', 'Team Member', 'Associate'],
  'cargo': ['Cargo', 'Position', 'Job Title', 'Role', 'Function'],
  'funcao': ['Função', 'Function', 'Role', 'Responsibility'],
  'salario': ['Salário', 'Salary', 'Wage', 'Pay', 'Compensation'],
  'remuneracao': ['Remuneração', 'Compensation', 'Payment', 'Remuneration'],
  'beneficio': ['Benefício', 'Benefit', 'Perk', 'Advantage'],
  'ferias': ['Férias', 'Vacation', 'Holiday', 'Leave', 'Time Off'],
  'licenca_rh': ['Licença', 'Leave', 'Time Off', 'Absence'],
  'atestado': ['Atestado', 'Medical Certificate', 'Health Certificate'],
  'falta': ['Falta', 'Absence', 'No Show', 'Missing'],
  'atraso': ['Atraso', 'Late', 'Delay', 'Tardiness'],
  'overtime': ['Hora Extra', 'Overtime', 'Extra Hours', 'Additional Hours'],
  'departamento': ['Departamento', 'Department', 'Division', 'Area'],
  'equipe': ['Equipe', 'Team', 'Group', 'Squad'],
  'gerente': ['Gerente', 'Manager', 'Supervisor', 'Chief'],
  'diretor': ['Diretor', 'Director', 'Executive', 'Head'],
  'presidente': ['Presidente', 'President', 'CEO', 'Chief Executive'],
  'admissao': ['Admissão', 'Hiring', 'Onboarding', 'Employment'],
  'demissao': ['Demissão', 'Termination', 'Dismissal', 'Firing'],
  'rescisao': ['Rescisão', 'Contract Termination', 'Employment End'],
  'contrato': ['Contrato', 'Contract', 'Agreement', 'Employment Contract'],
  'clt': ['CLT', 'Labor Law', 'Employment Law', 'Work Contract'],
  'pj': ['PJ', 'Pessoa Jurídica', 'Contractor', 'Legal Entity'],
  'terceirizado': ['Terceirizado', 'Outsourced', 'Contractor', 'External'],
  'estagiario': ['Estagiário', 'Intern', 'Trainee', 'Student'],
  'trainee': ['Trainee', 'Graduate Program', 'Junior Professional'],
  'avaliacao': ['Avaliação', 'Performance Review', 'Assessment', 'Evaluation'],
  'treinamento': ['Treinamento', 'Training', 'Development', 'Course'],
  'capacitacao': ['Capacitação', 'Training', 'Skill Development', 'Qualification'],
  'competencia': ['Competência', 'Skill', 'Competency', 'Ability'],
  'habilidade': ['Habilidade', 'Skill', 'Ability', 'Talent'],
  'experiencia': ['Experiência', 'Experience', 'Background', 'Expertise'],
  'curriculo': ['Currículo', 'Resume', 'CV', 'Curriculum Vitae'],
  'entrevista': ['Entrevista', 'Interview', 'Meeting', 'Assessment'],
  'selecao': ['Seleção', 'Selection', 'Recruitment', 'Hiring Process'],
  'recrutamento': ['Recrutamento', 'Recruitment', 'Hiring', 'Talent Acquisition'],
  'folha_pagamento': ['Folha de Pagamento', 'Payroll', 'Salary Sheet'],
  'inss': ['INSS', 'Social Security', 'Social Insurance'],
  'fgts': ['FGTS', 'Severance Fund', 'Employment Fund'],
  'vale_transporte': ['Vale Transporte', 'Transportation Voucher', 'Transport Benefit'],
  'vale_refeicao': ['Vale Refeição', 'Meal Voucher', 'Food Benefit'],
  'vale_alimentacao': ['Vale Alimentação', 'Food Voucher', 'Grocery Benefit'],
  'plano_saude': ['Plano de Saúde', 'Health Insurance', 'Medical Plan'],
  'plano_odontologico': ['Plano Odontológico', 'Dental Plan', 'Dental Insurance'],
  'seguro_vida': ['Seguro de Vida', 'Life Insurance', 'Life Coverage'],
  'auxilio_creche': ['Auxílio Creche', 'Daycare Assistance', 'Childcare Benefit'],
  'participacao_lucros': ['Participação nos Lucros', 'Profit Sharing', 'PLR'],
  'premio': ['Prêmio', 'Award', 'Bonus', 'Prize'],
  'promocao_rh': ['Promoção', 'Promotion', 'Career Advancement'],

  # VENDAS E MARKETING
  'vendas': ['Vendas', 'Sales', 'Revenue', 'Selling'],
  'cliente': ['Cliente', 'Customer', 'Client', 'Consumer'],
  'prospect': ['Prospect', 'Lead', 'Potential Customer', 'Target'],
  'lead': ['Lead', 'Prospect', 'Contact', 'Potential Client'],
  'campanha': ['Campanha', 'Campaign', 'Marketing Campaign', 'Promotion'],
  'promocao': ['Promoção', 'Promotion', 'Offer', 'Sale'],
  'desconto_marketing': ['Desconto', 'Discount', 'Sale', 'Rebate'],
  'produto': ['Produto', 'Product', 'Item', 'Merchandise'],
  'servico': ['Serviço', 'Service', 'Solution'],
  'marca': ['Marca', 'Brand', 'Trademark', 'Label'],
  'segmento_marketing': ['Segmento', 'Segment', 'Target', 'Market Segment'],
  'publico_alvo': ['Público Alvo', 'Target Audience', 'Target Market'],
  'conversion': ['Conversão', 'Conversion Rate', 'Sales Conversion'],
  'roi_marketing': ['ROI', 'Return on Investment', 'Marketing ROI'],
  'vendedor': ['Vendedor', 'Salesperson', 'Sales Rep', 'Account Executive'],
  'comissao': ['Comissão', 'Commission', 'Sales Commission'],
  'meta': ['Meta', 'Goal', 'Target', 'Objective'],
  'pedido': ['Pedido', 'Order', 'Purchase Order', 'Request'],
  'proposta': ['Proposta', 'Proposal', 'Quote', 'Offer'],
  'negociacao': ['Negociação', 'Negotiation', 'Deal'],
  'fechamento': ['Fechamento', 'Closing', 'Deal Close', 'Sale Close'],
  'pipeline': ['Pipeline', 'Sales Pipeline', 'Funnel'],
  'crm': ['CRM', 'Customer Relationship Management', 'Client Management'],
  'seo': ['SEO', 'Search Engine Optimization', 'Search Optimization'],
  'sem': ['SEM', 'Search Engine Marketing', 'Paid Search'],
  'email_marketing': ['Email Marketing', 'Newsletter', 'Email Campaign'],
  'redes_sociais': ['Redes Sociais', 'Social Media', 'Social Networks'],
  'influencer': ['Influencer', 'Digital Influencer', 'Content Creator'],

  # PRODUÇÃO E OPERAÇÕES
  'producao': ['Produção', 'Production', 'Manufacturing', 'Output'],
  'operacao': ['Operação', 'Operation', 'Process', 'Activity'],
  'processo': ['Processo', 'Process', 'Procedure', 'Method'],
  'qualidade': ['Qualidade', 'Quality', 'Standard', 'Excellence'],
  'estoque': ['Estoque', 'Inventory', 'Stock', 'Storage'],
  'fornecedor': ['Fornecedor', 'Supplier', 'Vendor', 'Provider'],
  'materia_prima': ['Matéria Prima', 'Raw Material', 'Input Material'],
  'capacidade': ['Capacidade', 'Capacity', 'Volume', 'Output Capacity'],
  'producao_diaria': ['Produção Diária', 'Daily Production', 'Daily Output'],
  'eficiencia': ['Eficiência', 'Efficiency', 'Performance', 'Effectiveness'],
  'produtividade': ['Produtividade', 'Productivity', 'Output Rate'],
  'linha_producao': ['Linha de Produção', 'Production Line', 'Assembly Line'],
  'maquina': ['Máquina', 'Machine', 'Equipment', 'Machinery'],
  'equipamento': ['Equipamento', 'Equipment', 'Tool', 'Device'],
  'manutencao': ['Manutenção', 'Maintenance', 'Service', 'Repair'],
  'inspecao': ['Inspeção', 'Inspection', 'Quality Check', 'Review'],
  'teste': ['Teste', 'Test', 'Testing', 'Quality Test'],
  'defeito': ['Defeito', 'Defect', 'Flaw', 'Quality Issue'],
  'lote': ['Lote', 'Batch', 'Lot', 'Production Batch'],
  'serial': ['Serial', 'Serial Number', 'Product Serial'],
  'codigo_barras': ['Código de Barras', 'Barcode', 'Product Code'],
  'sku': ['SKU', 'Stock Keeping Unit', 'Product Code'],
  'ncm': ['NCM', 'Nomenclatura Comum do Mercosul', 'Product Classification'],

  # JURÍDICO E COMPLIANCE
  'contrato_juridico': ['Contrato', 'Contract', 'Agreement', 'Legal Agreement'],
  'lei': ['Lei', 'Law', 'Regulation', 'Legal Requirement'],
  'regulamentacao': ['Regulamentação', 'Regulation', 'Rule', 'Compliance Rule'],
  'compliance': ['Compliance', 'Conformidade', 'Legal Compliance'],
  'auditoria': ['Auditoria', 'Audit', 'Review', 'Legal Review'],
  'licenca_juridica': ['Licença', 'License', 'Permit', 'Authorization'],
  'alvara': ['Alvará', 'Permit', 'License', 'Municipal License'],
  'processo_juridico': ['Processo', 'Legal Process', 'Lawsuit', 'Legal Case'],
  'tribunal': ['Tribunal', 'Court', 'Legal Court'],
  'advogado': ['Advogado', 'Lawyer', 'Attorney', 'Legal Counsel'],
  'juridico': ['Jurídico', 'Legal', 'Law', 'Legal Affairs'],
  'legislacao': ['Legislação', 'Legislation', 'Legal Framework'],
  'norma': ['Norma', 'Standard', 'Regulation', 'Rule'],
  'clausula': ['Cláusula', 'Clause', 'Contract Term'],
  'termo': ['Termo', 'Term', 'Agreement Term'],
  'acordo': ['Acordo', 'Agreement', 'Settlement', 'Deal'],
  'arbitragem': ['Arbitragem', 'Arbitration', 'Mediation'],
  'mediacao': ['Mediação', 'Mediation', 'Settlement'],
  'multa_juridica': ['Multa', 'Fine', 'Legal Penalty', 'Sanction'],
  'sancao': ['Sanção', 'Sanction', 'Penalty', 'Fine'],

  # LOGÍSTICA E TRANSPORTE
  'entrega': ['Entrega', 'Delivery', 'Shipment', 'Distribution'],
  'frete': ['Frete', 'Freight', 'Shipping', 'Transport Cost'],
  'transportadora': ['Transportadora', 'Carrier', 'Shipping Company', 'Logistics'],
  'veiculo': ['Veículo', 'Vehicle', 'Transport', 'Truck'],
  'rota': ['Rota', 'Route', 'Path', 'Delivery Route'],
  'carga': ['Carga', 'Load', 'Cargo', 'Freight'],
  'peso': ['Peso', 'Weight', 'Mass'],
  'volume': ['Volume', 'Volume', 'Size', 'Capacity'],
  'prazo': ['Prazo', 'Deadline', 'Due Date', 'Lead Time'],
  'rastreamento': ['Rastreamento', 'Tracking', 'Trace', 'Follow-up'],
  'armazem': ['Armazém', 'Warehouse', 'Storage', 'Distribution Center'],
  'deposito': ['Depósito', 'Warehouse', 'Storage Facility'],
  'distribuicao': ['Distribuição', 'Distribution', 'Delivery Network'],
  'logistica': ['Logística', 'Logistics', 'Supply Chain'],
  'expedicao': ['Expedição', 'Shipping', 'Dispatch', 'Shipment'],
  'recebimento_logistica': ['Recebimento', 'Receiving', 'Intake'],
  'conferencia': ['Conferência', 'Checking', 'Verification', 'Inspection'],
  'separacao': ['Separação', 'Picking', 'Order Picking'],
  'embalagem': ['Embalagem', 'Packaging', 'Package', 'Wrapping'],
  'etiqueta': ['Etiqueta', 'Label', 'Tag', 'Shipping Label'],

  # DATAS E TEMPO
  'data': ['Data', 'Date', 'Day', 'Calendar Date'],
  'hora': ['Hora', 'Time', 'Hour', 'Clock Time'],
  'periodo': ['Período', 'Period', 'Time Frame', 'Duration'],
  'ano': ['Ano', 'Year', 'Annual'],
  'mes': ['Mês', 'Month', 'Monthly'],
  'dia': ['Dia', 'Day', 'Daily'],
  'semana': ['Semana', 'Week', 'Weekly'],
  'trimestre': ['Trimestre', 'Quarter', 'Quarterly'],
  'semestre': ['Semestre', 'Semester', 'Half-year'],
  'bimestre': ['Bimestre', 'Bi-monthly', 'Two Months'],
  'vencimento': ['Vencimento', 'Due Date', 'Expiration', 'Maturity'],
  'inicio': ['Início', 'Start', 'Beginning', 'Commencement'],
  'fim': ['Fim', 'End', 'Finish', 'Conclusion'],
  'duracao': ['Duração', 'Duration', 'Length', 'Time Span'],
  'cronograma': ['Cronograma', 'Schedule', 'Timeline', 'Timetable'],
  'agenda': ['Agenda', 'Schedule', 'Calendar', 'Appointment'],
  'prazo_final': ['Prazo Final', 'Final Deadline', 'End Date'],
  'timestamp': ['Timestamp', 'Time Stamp', 'Date Time'],

  # IDENTIFICAÇÃO E DOCUMENTOS
  'id': ['ID', 'Identificação', 'Código', 'Code', 'Identifier'],
  'codigo': ['Código', 'Code', 'ID', 'Reference'],
  'documento': ['Documento', 'Document', 'Paper', 'Record'],
  'cpf': ['CPF', 'Tax ID', 'Personal ID', 'Individual Registration'],
  'cnpj_doc': ['CNPJ', 'Corporate Tax ID', 'Company Registration'],
  'rg': ['RG', 'Identity Card', 'ID Card', 'National ID'],
  'passaporte': ['Passaporte', 'Passport', 'Travel Document'],
  'carteira_trabalho': ['Carteira de Trabalho', 'Work Permit', 'Labor Card'],
  'carteira_motorista': ['Carteira de Motorista', 'Driver License', 'CNH'],
  'titulo_eleitor': ['Título de Eleitor', 'Voter Registration', 'Electoral Title'],
  'certidao_nascimento': ['Certidão de Nascimento', 'Birth Certificate'],
  'certidao_casamento': ['Certidão de Casamento', 'Marriage Certificate'],
  'comprovante_residencia': ['Comprovante de Residência', 'Proof of Address'],
  'numero_documento': ['Número do Documento', 'Document Number'],
  'orgao_emissor': ['Órgão Emissor', 'Issuing Authority', 'Issuer'],
  'data_emissao': ['Data de Emissão', 'Issue Date', 'Issuance Date'],
  'data_validade': ['Data de Validade', 'Expiration Date', 'Valid Until'],

  # CONTATO E COMUNICAÇÃO
  'telefone': ['Telefone', 'Phone', 'Tel', 'Phone Number'],
  'celular': ['Celular', 'Mobile', 'Cell Phone', 'Mobile Phone'],
  'email': ['Email', 'E-mail', 'Electronic Mail', 'Email Address'],
  'site': ['Site', 'Website', 'Web', 'Homepage'],
  'whatsapp': ['WhatsApp', 'WA', 'WhatsApp Number'],
  'telegram': ['Telegram', 'Telegram Contact'],
  'skype': ['Skype', 'Skype ID'],
  'linkedin': ['LinkedIn', 'LinkedIn Profile'],
  'facebook': ['Facebook', 'Facebook Profile'],
  'instagram': ['Instagram', 'Instagram Profile', 'IG'],
  'twitter': ['Twitter', 'Twitter Profile', 'X'],
  'youtube': ['YouTube', 'YouTube Channel'],
  'tiktok': ['TikTok', 'TikTok Profile'],
  'discord': ['Discord', 'Discord Contact'],
  'slack': ['Slack', 'Slack Contact'],
  'teams': ['Teams', 'Microsoft Teams'],
  'zoom': ['Zoom', 'Zoom Meeting'],
  'ramal': ['Ramal', 'Extension', 'Phone Extension'],
  'fax': ['Fax', 'Fax Number'],
  'caixa_postal': ['Caixa Postal', 'PO Box', 'Mail Box'],

  # EDUCAÇÃO E FORMAÇÃO
  'educacao': ['Educação', 'Education', 'Learning', 'Academic Background'],
  'formacao': ['Formação', 'Education', 'Degree', 'Academic Formation'],
  'curso': ['Curso', 'Course', 'Program', 'Academic Course'],
  'certificacao': ['Certificação', 'Certification', 'Certificate', 'Professional Certificate'],
  'diploma': ['Diploma', 'Degree', 'Academic Diploma'],
  'universidade': ['Universidade', 'University', 'College', 'Higher Education'],
  'faculdade': ['Faculdade', 'College', 'Faculty', 'School'],
  'escola': ['Escola', 'School', 'Educational Institution'],
  'instituto': ['Instituto', 'Institute', 'Technical School'],
  'nivel': ['Nível', 'Level', 'Grade', 'Academic Level'],
  'nota': ['Nota', 'Grade', 'Score', 'Mark'],
  'disciplina': ['Disciplina', 'Subject', 'Course Subject'],
  'materia': ['Matéria', 'Subject', 'Course Material'],
  'professor': ['Professor', 'Teacher', 'Instructor'],
  'aluno': ['Aluno', 'Student', 'Pupil'],
  'graduacao': ['Graduação', 'Undergraduate', 'Bachelor Degree'],
  'pos_graduacao': ['Pós-Graduação', 'Graduate', 'Postgraduate'],
  'mestrado': ['Mestrado', 'Masters', 'Masters Degree'],
  'doutorado': ['Doutorado', 'PhD', 'Doctorate'],
  'especializacao': ['Especialização', 'Specialization', 'Professional Course'],
  'mba': ['MBA', 'Master of Business Administration'],
  'tecnico': ['Técnico', 'Technical', 'Technical Course'],
  'profissionalizante': ['Profissionalizante', 'Professional', 'Vocational'],
  'ead': ['EAD', 'Distance Learning', 'Online Education'],
  'presencial': ['Presencial', 'In-Person', 'Face-to-Face'],
  'hibrido': ['Híbrido', 'Hybrid', 'Blended Learning'],

  # SAÚDE E SEGURANÇA
  'saude': ['Saúde', 'Health', 'Healthcare', 'Medical'],
  'seguranca': ['Segurança', 'Security', 'Safety', 'Protection'],
  'medicina_trabalho': ['Medicina do Trabalho', 'Occupational Health', 'Work Medicine'],
  'exame_medico': ['Exame Médico', 'Medical Exam', 'Health Check'],
  'exame_admissional': ['Exame Admissional', 'Pre-employment Medical'],
  'exame_periodico': ['Exame Periódico', 'Periodic Medical Exam'],
  'exame_demissional': ['Exame Demissional', 'Exit Medical Exam'],
  'acidente': ['Acidente', 'Accident', 'Incident', 'Work Accident'],
  'acidente_trabalho': ['Acidente de Trabalho', 'Work Accident', 'Occupational Accident'],
  'epi': ['EPI', 'Personal Protective Equipment', 'Safety Equipment'],
  'epc': ['EPC', 'Collective Protective Equipment'],
  'cipa': ['CIPA', 'Safety Committee', 'Accident Prevention Committee'],
  'brigada': ['Brigada', 'Emergency Team', 'Fire Brigade'],
  'sesmt': ['SESMT', 'Occupational Safety Service'],
  'nr': ['NR', 'Regulatory Standard', 'Safety Standard'],
  'cat': ['CAT', 'Work Accident Report'],
  'pcmso': ['PCMSO', 'Medical Control Program'],
  'ppra': ['PPRA', 'Environmental Risk Prevention Program'],
  'ltcat': ['LTCAT', 'Technical Report on Working Conditions'],
  'ppp': ['PPP', 'Occupational Profile Form'],
  'aso': ['ASO', 'Occupational Health Certificate'],
  'laudo': ['Laudo', 'Technical Report', 'Medical Report'],
  'risco': ['Risco', 'Risk', 'Hazard', 'Safety Risk'],
  'periculosidade': ['Periculosidade', 'Hazard Pay', 'Dangerous Work'],
  'insalubridade': ['Insalubridade', 'Unhealthy Work', 'Health Hazard'],

  # TECNOLOGIA ESPECÍFICA
  'cloud': ['Cloud', 'Nuvem', 'Cloud Computing', 'Cloud Service'],
  'saas': ['SaaS', 'Software as a Service', 'Cloud Software'],
  'paas': ['PaaS', 'Platform as a Service', 'Cloud Platform'],
  'iaas': ['IaaS', 'Infrastructure as a Service', 'Cloud Infrastructure'],
  'devops': ['DevOps', 'Development Operations', 'Dev Ops'],
  'agile': ['Agile', 'Ágil', 'Metodologia Ágil', 'Agile Methodology'],
  'scrum': ['Scrum', 'Framework Scrum', 'Scrum Method'],
  'kanban': ['Kanban', 'Metodologia Kanban', 'Kanban Board'],
  'sprint': ['Sprint', 'Iteration', 'Development Sprint'],
  'repository': ['Repositório', 'Repository', 'Repo', 'Code Repository'],
  'git': ['Git', 'Version Control', 'Source Control'],
  'github': ['GitHub', 'Git Hub', 'Code Platform'],
  'gitlab': ['GitLab', 'Git Lab'],
  'bitbucket': ['Bitbucket', 'Bit Bucket'],
  'docker': ['Docker', 'Container', 'Containerization'],
  'kubernetes': ['Kubernetes', 'K8s', 'Orchestration', 'Container Orchestration'],
  'jenkins': ['Jenkins', 'CI/CD', 'Continuous Integration'],
  'terraform': ['Terraform', 'Infrastructure as Code'],
  'ansible': ['Ansible', 'Configuration Management'],
  'aws': ['AWS', 'Amazon Web Services', 'Amazon Cloud'],
  'azure': ['Azure', 'Microsoft Azure', 'Azure Cloud'],
  'gcp': ['GCP', 'Google Cloud Platform', 'Google Cloud'],
  'microservicos': ['Microserviços', 'Microservices', 'Micro Services'],
  'rest': ['REST', 'RESTful', 'REST API'],
  'graphql': ['GraphQL', 'Graph QL'],
  'json': ['JSON', 'JavaScript Object Notation'],
  'xml': ['XML', 'Extensible Markup Language'],
  'yaml': ['YAML', 'YAML Configuration'],
  'ssl_tec': ['SSL', 'TLS', 'Security Certificate'],
  'oauth': ['OAuth', 'Authentication Protocol'],
  'jwt': ['JWT', 'JSON Web Token'],
  'cdn': ['CDN', 'Content Delivery Network'],
  'load_balancer': ['Load Balancer', 'Balanceador de Carga'],

  # CONTABILIDADE
  'contabilidade': ['Contabilidade', 'Accounting', 'Bookkeeping'],
  'contador': ['Contador', 'Accountant', 'CPA'],
  'balanco': ['Balanço', 'Balance Sheet', 'Financial Statement'],
  'dre': ['DRE', 'Demonstração do Resultado', 'Income Statement'],
  'dfc': ['DFC', 'Demonstração do Fluxo de Caixa', 'Cash Flow Statement'],
  'dmpl': ['DMPL', 'Demonstração das Mutações do Patrimônio Líquido'],
  'dva': ['DVA', 'Demonstração do Valor Adicionado'],
  'razao': ['Razão', 'General Ledger', 'Ledger'],
  'diario': ['Diário', 'Journal', 'Accounting Journal'],
  'lancamento': ['Lançamento', 'Entry', 'Accounting Entry'],
  'debito_contabil': ['Débito', 'Debit', 'Debit Entry'],
  'credito_contabil': ['Crédito', 'Credit', 'Credit Entry'],
  'plano_contas': ['Plano de Contas', 'Chart of Accounts', 'Account Plan'],
  'centro_custo': ['Centro de Custo', 'Cost Center', 'Department Code'],
  'depreciacao': ['Depreciação', 'Depreciation', 'Asset Depreciation'],
  'amortizacao': ['Amortização', 'Amortization', 'Loan Amortization'],
  'provisao': ['Provisão', 'Provision', 'Reserve'],
  'accrual': ['Competência', 'Accrual', 'Accrual Basis'],
  'regime_caixa': ['Regime de Caixa', 'Cash Basis', 'Cash Accounting'],
  'sped': ['SPED', 'Sistema Público de Escrituração Digital'],
  'ecf': ['ECF', 'Escrituração Contábil Fiscal'],
  'ecd': ['ECD', 'Escrituração Contábil Digital'],

  # TRIBUTOS E IMPOSTOS
  'imposto': ['Imposto', 'Tax', 'Taxation', 'Levy'],
  'tributo': ['Tributo', 'Tax', 'Tribute', 'Government Tax'],
  'icms': ['ICMS', 'Tax on Circulation of Goods and Services'],
  'ipi': ['IPI', 'Tax on Industrialized Products'],
  'iss': ['ISS', 'Service Tax', 'Municipal Service Tax'],
  'pis': ['PIS', 'Social Integration Program'],
  'cofins': ['COFINS', 'Social Security Financing Contribution'],
  'csll': ['CSLL', 'Social Contribution on Net Profits'],
  'irpj': ['IRPJ', 'Corporate Income Tax'],
  'irrf': ['IRRF', 'Withholding Income Tax'],
  'inss_empresa': ['INSS Empresa', 'Company Social Security'],
  'fgts_empresa': ['FGTS Empresa', 'Company Severance Fund'],
  'simples': ['Simples', 'Simplified Tax System', 'Simples Nacional'],
  'lucro_real': ['Lucro Real', 'Actual Profit', 'Real Profit Taxation'],
  'lucro_presumido': ['Lucro Presumido', 'Presumed Profit'],
  'mei': ['MEI', 'Individual Microentrepreneur'],
  'microempresa': ['Microempresa', 'Microenterprise', 'Small Business'],
  'epp': ['EPP', 'Empresa de Pequeno Porte', 'Small Company'],
  'regime_tributario': ['Regime Tributário', 'Tax System', 'Tax Regime'],
  'aliquota': ['Alíquota', 'Tax Rate', 'Rate'],
  'base_calculo': ['Base de Cálculo', 'Tax Base', 'Calculation Base'],
  'isencao': ['Isenção', 'Exemption', 'Tax Exemption'],
  'reducao': ['Redução', 'Reduction', 'Tax Reduction'],
  'substituicao_tributaria': ['Substituição Tributária', 'Tax Substitution'],

  # PROJETOS E GESTÃO
  'projeto': ['Projeto', 'Project', 'Initiative'],
  'gerenciamento': ['Gerenciamento', 'Management', 'Project Management'],
  'cronograma_projeto': ['Cronograma', 'Schedule', 'Project Timeline'],
  'milestone': ['Marco', 'Milestone', 'Key Milestone'],
  'entregavel': ['Entregável', 'Deliverable', 'Project Deliverable'],
  'stakeholder': ['Stakeholder', 'Interessado', 'Project Stakeholder'],
  'sponsor': ['Patrocinador', 'Sponsor', 'Project Sponsor'],
  'escopo': ['Escopo', 'Scope', 'Project Scope'],
  'requisito': ['Requisito', 'Requirement', 'Project Requirement'],
  'risco_projeto': ['Risco', 'Risk', 'Project Risk'],
  'issue': ['Problema', 'Issue', 'Project Issue'],
  'mudanca': ['Mudança', 'Change', 'Change Request'],
  'baseline': ['Baseline', 'Linha de Base', 'Project Baseline'],
  'gantt': ['Gantt', 'Gráfico de Gantt', 'Gantt Chart'],
  'pert': ['PERT', 'Program Evaluation Review Technique'],
  'wbs': ['WBS', 'Work Breakdown Structure', 'Estrutura Analítica'],
  'pmo': ['PMO', 'Project Management Office'],
  'kpi_projeto': ['KPI', 'Key Performance Indicator', 'Indicador'],
  'dashboard': ['Dashboard', 'Painel', 'Control Panel'],
  'report': ['Relatório', 'Report', 'Project Report'],

  # QUALIDADE E CERTIFICAÇÕES
  'iso': ['ISO', 'International Organization for Standardization'],
  'iso_9001': ['ISO 9001', 'Quality Management System'],
  'iso_14001': ['ISO 14001', 'Environmental Management'],
  'iso_45001': ['ISO 45001', 'Occupational Health and Safety'],
  'iso_27001': ['ISO 27001', 'Information Security Management'],
  'seis_sigma': ['Seis Sigma', 'Six Sigma', 'Quality Improvement'],
  'lean': ['Lean', 'Lean Manufacturing', 'Lean Management'],
  'kaizen': ['Kaizen', 'Continuous Improvement'],
  'pdca': ['PDCA', 'Plan-Do-Check-Act', 'Quality Cycle'],
  'dmaic': ['DMAIC', 'Define-Measure-Analyze-Improve-Control'],
  'certificacao_qualidade': ['Certificação', 'Certification', 'Quality Certificate'],
  'auditoria_qualidade': ['Auditoria', 'Audit', 'Quality Audit'],
  'ncr': ['NCR', 'Non-Conformity Report', 'Não Conformidade'],
  'acao_corretiva': ['Ação Corretiva', 'Corrective Action'],
  'acao_preventiva': ['Ação Preventiva', 'Preventive Action'],
  'melhoria_continua': ['Melhoria Contínua', 'Continuous Improvement'],

  # MEIO AMBIENTE E SUSTENTABILIDADE
  'meio_ambiente': ['Meio Ambiente', 'Environment', 'Environmental'],
  'sustentabilidade': ['Sustentabilidade', 'Sustainability', 'Sustainable'],
  'licenca_ambiental': ['Licença Ambiental', 'Environmental License'],
  'impacto_ambiental': ['Impacto Ambiental', 'Environmental Impact'],
  'gestao_residuos': ['Gestão de Resíduos', 'Waste Management'],
  'reciclagem': ['Reciclagem', 'Recycling', 'Recycle'],
  'energia_renovavel': ['Energia Renovável', 'Renewable Energy'],
  'carbono': ['Carbono', 'Carbon', 'Carbon Footprint'],
  'pegada_carbono': ['Pegada de Carbono', 'Carbon Footprint'],
  'sustentavel': ['Sustentável', 'Sustainable', 'Green'],
  'verde': ['Verde', 'Green', 'Eco-friendly'],
  'esg': ['ESG', 'Environmental Social Governance'],
  'responsabilidade_social': ['Responsabilidade Social', 'Social Responsibility'],

  # COMUNICAÇÃO INTERNA
  'comunicacao': ['Comunicação', 'Communication', 'Internal Communication'],
  'reuniao': ['Reunião', 'Meeting', 'Conference'],
  'apresentacao': ['Apresentação', 'Presentation', 'Pitch'],
  'relatorio': ['Relatório', 'Report', 'Document'],
  'ata': ['Ata', 'Minutes', 'Meeting Minutes'],
  'memo': ['Memorando', 'Memo', 'Internal Memo'],
  'circular': ['Circular', 'Circular Letter', 'Company Notice'],
  'comunicado': ['Comunicado', 'Notice', 'Announcement'],
  'newsletter': ['Newsletter', 'Company Newsletter'],
  'intranet': ['Intranet', 'Internal Network', 'Company Portal'],
  'portal': ['Portal', 'Company Portal', 'Internal Portal'],
  'video_conferencia': ['Videoconferência', 'Video Conference', 'Online Meeting'],
  'webinar': ['Webinar', 'Online Seminar', 'Web Seminar']
}

def detect_column_types(df):
    """
    Retorna para cada coluna do DataFrame o seu 'tipo' (key do dicionário) OU None se não encontrado.
    Exemplo de saída: {'CEP': 'cep', 'Endereço': 'endereco', 'CNPJ': 'cnpj', ...}
    """
    col_map = {}
    for col in df.columns:
        col_norm = unidecode.unidecode(str(col)).lower().strip()
        found = None
        for tipo, sin_list in DOMAIN_SYNONYMS.items():
            for sin in sin_list:
                sin_norm = unidecode.unidecode(str(sin)).lower().strip()
                # Aceita igual ou inicia igual (ex: 'Endereço' pega 'Endereço Completo')
                if col_norm == sin_norm or col_norm.startswith(sin_norm):
                    found = tipo
                    break
            if found:
                break
        col_map[col] = found  # tipo (ex: 'cep') ou None
    return col_map
